server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    max-idle: 10
    min-idle: 5
    initial-size: 5
    max-wait: 10000
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application

mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com:
      example:
        demo:
          mapper: debug